### ISSUE TITLE
InternalCompilerError: Internal compiler error (/solidity/libsolidity/codegen/ContractCompiler.cpp:1398)

### ISSUE THREAD

**Issue by ItsShadowl** [ethereum/solidity#11723]
## Description

While compiling some multiple files, with hardhat, this error popped up failing to compile the smart contracts

https://github.com/ethereum/solidity/blob/3c350a63f1190e27a2f5916bcaec7396c0c176f1/libsolidity/codegen/ContractCompiler.cpp#L1398

## Environment
- 0.8.4
- Target EVM version (as per compiler settings): instanbul
- Framework/IDE (e.g. Truffle or Remix): hardhat
- EVM execution environment / backend / blockchain client: hardhat
- Operating system: WSL

## Steps to Reproduce
```solidity
// I don't know what kind of file to past to reproduce since the compiler error isn't informative or suggesting one
// ...
```

**Comment by cameel** [comment]
Since it happens on 0.8.4 it's actually this line: https://github.com/ethereum/solidity/blob/c7e474f243fa6bd6d6c172118b95d52113b5fbad/libsolidity/codegen/ContractCompiler.cpp#L1398

Looks like it's caused by applying a modifier to a function that has no body.

The bug might actually be already fixed. In 0.8.5 we fixed a bunch of bugs related to unimplemented modifiers and functions (#11468, #11445). There was also #11506 which is fixed too but the fix will be a part of 0.8.7.

Can you check if it still crashes for you on 0.8.6 (or, preferably on the latest nightly version if possible)?

If it still happens on 0.8.6 we could investigate further but we'd need some code to be able to replicate this.

**Comment by ItsShadowl** [comment]
Thanks for the quick reply...

Actually, i have modifiers in so many functions without body and after placing the variables in the empty body, i'm still facing the error...

I tried compiling with 0.8.5 or 0.8.6, but hardhat and Openzeppelin are giving me issues too, so i'm stuck with splitting the projects to different parts so i can figure out the exact code throwing the exception and using 0.8.4 for now until there's support for it in the dependencies i'm using

**Comment by ItsShadowl** [comment]
After splitting the projects, i didn't see any of it reporting the same error again maybe i've unknowingly fixed it somehow...
So, i would take it as no problem for now and close the issue

**Comment by ItsShadowl** [comment]
Still on 0.8.4 since tooling i depend on aren't ready for .5 or .6 yet

**Comment by ItsShadowl** [comment]
Figured out the problem.
It was because I overwrite'd a function in multiple places, and it isn't an abstract contract or a virtual function.

**Comment by ItsShadowl** [comment]
I can gather example, but it should be a common mistake and the error message should have been clear

**Comment by jackliu8722** [comment]
i meet the same problem, for version 0.7.3

**Comment by ItsShadowl** [comment]
The problem was because a smart contract declared a function and it was overwritten in the main contract, whereas the main contract implements two interface that both declared the function defined in the first smart contract

```
SmartContract1 -> balanceOf()
ISmartContract1 -> balanceOf()
IMainSmartContract -> override balanceOf()
MainSmartContract is SmartContract1, ISmartContract1, IMainSmartContract -> override(ISmartContract1, IMainSmartContract, SmartContract1) balanceOf
```

I hope my analogy can be understood?

Couldn't get the right example from my local git immediately

**Comment by ItsShadowl** [comment]
So, i had to remove the definition from the IMainSmartContract, then make IMainSmartContract inherit it directly from ISmartContract1 to get the problem solved

**Comment by cameel** [comment]
@noobshow I'm trying to understand your example but I cannot reproduce the error with that on 0.8.4. I'd like to reproduce it to make sure the problem is indeed fixed.

From what you posted I gather that your hierarchy looks something like this?
```solidity
interface ISmartContract1 {
    function balanceOf() external view;
}
interface IMainSmartContract {
    function balanceOf() external view;
}
contract SmartContract1 {
    function balanceOf() external view virtual {}
}
contract MainSmartContract is SmartContract1, ISmartContract1, IMainSmartContract {
    function balanceOf() external view override(ISmartContract1, IMainSmartContract, SmartContract1) {}
}
```

Is `SmartContract1` supposed to inherit from one of the interfaces? Because if it's not, you cannot use `override` on its `balanceOf()` as in your description.

I think I must be getting it wrong because this does not cause a crash for me. It would if you used `super` (like in #11445) but it would produce an error at a different location in the code. It would make sense if adding a modifier would make it crash but adding one on `MainSmartContract.balanceOf()` does not make it crash either.

So could you adjust this snippet to reproduce your error?

> So, i had to remove the definition from the IMainSmartContract, then make IMainSmartContract inherit it directly from ISmartContract1 to get the problem solved

That's a good workaround but I think an even simpler one would work. The problem that's causing the crash is likely just the order in which you inherit. A more sensible order would be `is ISmartContract1, IMainSmartContract, SmartContract1` because then all the interfaces would go before contracts that implement them. The way you did it, however, results in a linearized order where `super.balanceOf()` inside `SmartContract1.balanceOf()` would call `IMainSmartContract.balanceOf()`, which has no body. While weird, it's still allowed - `super` should skip over a function without a body - it's just that the compiler was not handling that corner case correctly (this was the bug in #11445).

So I'm not yet sure how he crash worked exactly in your case but I think that the problem would disappear if you used the  inheritance order that does not produce this corner case (i.e. `is ISmartContract1, IMainSmartContract, SmartContract1`).

**Comment by cameel** [comment]
@jackliu8722 Can you reproduce it on 0.8.7? We're not backporting bugfixes to older compiler versions.

But it would still be very helpful if you could post a snippet that reproduces it with 0.7.3.

**Comment by ItsShadowl** [comment]
Testing your example, i think i should try gather the actual example... It's as similar as what you posted above, just a lil' bit difference which i should point out soon...

Thanks for taking the time.

**Comment by ItsShadowl** [comment]
```solidity
//SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.0;

interface IERC20 {
    function balanceOf() external view;
}

interface ISmartContract1 is IERC20 {
    // function balanceOf() external view;
}

interface IMainSmartContract is ISmartContract1 {
    function balanceOf() external view override;
}

contract ERC20 is IERC20 {
    function balanceOf() external virtual view override  {
    }
}

abstract contract SmartContract1 is ERC20, ISmartContract1 {
    
}

contract MainSmartContract is SmartContract1, IMainSmartContract {
    function balanceOf() external view override(IMainSmartContract, ERC20) {
        
    }
}

```

I couldn't get it buggy back, but its more like this above

**Comment by ItsShadowl** [comment]
The buggy function has this in override list from the git history i was able to pull up 
```

	function balanceOf()
		public
		view
		override(IERC20Upgradeable, ERC20, IMainSmartContract)
	{
        }
```

**Comment by cameel** [comment]
So there were no modifiers? I played with this a bit but I cannot reproduce it either and I really can't see why you would run into this ICE without modifiers.

Well, if anyone can provide a failing example, I'll look into it. Hopefully the recent fixes did change it and everything is ok.

**Comment by ItsShadowl** [comment]
I'm not sure if the problem relates to modifiers as i implemented all modifiers and made sure its not used on an empty body, in fact the error didn't stop when i was playing with modifiers, it stopped after i removed the duplicate declarations in an interface...

I rechecked it was the reason by returning it and seeing if the error still pop up, then it did... 
Had it in mind to share with this issue, but was so busy till i overwrote the implementation fully and now couldn't reproduce it.

I'm sorry for this, so sorry i couldn't reproduce it all way i could remember.
