### ISSUE TITLE
Easy type-safe encoding a method call.

### ISSUE THREAD

**Issue by drortirosh** [ethereum/solidity#11849]
Decision: Add `abi.encodeCall(f, (arg1, arg2))`
Check that `abi.encodeCall(f, ())` also works.

---

In modern solidity code, it is very common to pass encoded function to other solidity contract for multiple purposes (delayed operation, adding access-control, meta-transactions, etc)

something similar to
```solidity
someContract.executeLater(target,
    abi.encodeWithSelector(MyContract.myMethod.selector, param1, uint(param2)) ); 
```

however, using encodeWithSelector is very error-prone: there is no type checking, and no tell if the method signature is modified.

### Suggestion:
add a syntactic sugar encoder, so that the above can be written like this:
```solidity
someContract.executeLater(target,
    MyContract.myMethod.encode(param1, uint(param2)) ); 
```

The output of such "method call" is just like of encodeWithSelector - a `bytes memory`
The only difference is clearer clearer syntax and type-checking.

Note that it is a "method call" of a contract type, not an instance: just like encodeWithAbi, there is no contract instance involved.

**Comment by cameel** [comment]
This sounds interesting. We'd like to get more feedback on that though so I have posted it to the forum: [Helper for type-safe ABI-encoding of function calls](https://forum.soliditylang.org/t/helper-for-type-safe-abi-encoding-of-function-calls/493).

**Comment by axic** [comment]
Another potential option if we want to stay within the `abi` namespace: `abi.encodeCall(func, ...args)`

**Comment by GNSPS** [comment]
I love this! ❤️

**Comment by transmissions11** [comment]
Yes this would be fantastic!! Posted reasons on the forum: https://forum.soliditylang.org/t/helper-for-type-safe-abi-encoding-of-function-calls/493/3?u=transmissions11

**Comment by transmissions11** [comment]
> Another potential option if we want to stay within the `abi` namespace: `abi.encodeCall(func, ...args)`

i think one of the main strengths of @drortirosh's proposed syntax is that it's concise and familiar

really not a fan of `abi.encodeCall`, since for the use-cases we're envisioning here we want to make it **easier** for devs to access bytes encoded function calls.

requiring them to use an obscure `abi.encodeCall` function that looks nothing like normal function call syntax is super off-putting, which seems unnecessary because the proposed logic is not unsafe/risky.

**Comment by ekpyron** [comment]
I like the proposal and the syntax a lot - however, annoyingly the proposed syntax would strictly speaking be a breaking change due to weird constructs like this:
```
library L {
    function encode(function() external) internal pure returns (uint256) {
        return 42;
    }
}

contract C {
    using L for function() external;

    function f() public returns (uint256) {
        return this.f.encode();
    }
}
```
(off topic, but actually being able to implement such an encoding function generically for all function types in the language itself in the future might be a good stress-test for any proposal for upcoming generics in the language)

**Comment by ekpyron** [comment]
Actually, what I said only applies for adding ``encode`` to an actually externally callable function, i.e. a member of a function accessed in an instance of a contract, not the contract type. So in my previous example ``C.f.encode();`` would still be fine.
However, that way, ``encode`` would become inaccessible in some inheritance situations, e.g.
```
contract C {
    function f() public {
    }
}

contract D is C {
    function g() public {
        C.f.encode();
    }
}
```
Since here ``C.f`` is an internal function and there is no way to access the external function using the contract type in this situation.
Not sure how big of a problem that is, though.

We could of course get around this by also adding the member to internal function types, but then it becomes strictly speaking breaking again...

In any case: my point is: we need to be a bit careful about this.

**Comment by ekpyron** [comment]
There is precedent for ignoring this to be strictly speaking breaking when we introduced ``.selector`` in the inheritance case with 0.6.2.

**Comment by chriseth** [comment]
> > Another potential option if we want to stay within the `abi` namespace: `abi.encodeCall(func, ...args)`
> 
> i think one of the main strengths of @drortirosh's proposed syntax is that it's concise and familiar
> 
> really not a fan of `abi.encodeCall`, since for the use-cases we're envisioning here we want to make it **easier** for devs to access bytes encoded function calls.
> 
> requiring them to use an obscure `abi.encodeCall` function that looks nothing like normal function call syntax is super off-putting, which seems unnecessary because the proposed logic is not unsafe/risky.

I would actually say that it is good that it looks nothing like a normal function call is good, because it is not a normal function call, it just encodes the data for the function call and why not put this into the `abi` "namespace"? Although I do see the problem of putting the function and the arguments at the same level.

`f.encode` might be a bit too generic for my taste - what about `f.abiEncode(arg1, ..., argn)`?

**Comment by axic** [comment]
One argument for keeping it in `abi.` is that a function call statement is not only about encoding of data, but checking the return value and decoding the returned data. When someone just encodes one part of that and passes it around, the checks done after execution are not part of the statement anymore. Hence it is a "risky" task and works the same way other `abi.` methods do. Users of the language are already familiar what to do with `abi.` methods.

> Although I do see the problem of putting the function and the arguments at the same level.

We already have types added in `abi.decode` to be fair, although one confusion may be that we do accept function types and `abi.encodeCall(f, ...)` kind of looks like a function type. However, there are already special encoders, like `encodeWithSelector` and `encodeWithSignature` which treat their first parameter in a special way.

**Comment by axic** [comment]
While I think this feature is definitely useful, it would be nice to see more actual examples how this is used today. We did a search on GitHub and a lot of uses of `abi.encodeWithSelector` are combined with `.staticcall`/`.delegatecall`, which makes me wonder whether the majority of cases requiring this actually just require an override for calls?

Such as `f{mutability: view}()` or `f{callmode: view}`, etc.

**Comment by drortirosh** [comment]
Yes, eventually, the encoded function is passed to a `staticcall` or `delegatecall`, but not always directly. 
e.g.: 
When using a factory or proxy contract (like [this](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/ERC1967/ERC1967Proxy.sol#L21)), it is often that you pass in an "initCode" parameter, which gets executed  just after creating the new contract.
There are other use-cases, too.

**Comment by axic** [comment]
> When using a "factory", contract (like this), it is often that you pass in an "initCode" parameter, which the factory will execute after creating the new contract.

If I'm not mistaken the `initCode` here is actually a contract code and not an ABI encoded function call.

**Comment by cameel** [comment]
I noticed today that OpenZeppelin's [`SafeERC20`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol) is also doing a lot of call encoding so it would be another use case.

**Comment by drortirosh** [comment]
> > When using a "factory", contract (like this), it is often that you pass in an "initCode" parameter, which the factory will execute after creating the new contract.
> 
> If I'm not mistaken the `initCode` here is actually a contract code and not an ABI encoded function call.

you're right... pointed to the wrong example. my mistake...
I fixed the link above, so now it points to a better example.

**Comment by axic** [comment]
On yesterday's meeting it was discussed that this feature feels useful, even if many use cases combine `encodeWithSelector` with `.staticcall`/`.delegatecall`, for which we don't think this is the right feature.

However because we want to show it is a "risky" step to do, the syntax of `abi.encodeCall` (or something similar within the `abi` namespace) seems like the better choice. And in case it turns out not to be useful feature, deprecating from within `abi` is easier.

Lastly in case arguments are not entirely clear, we could consider a syntax like `abi.encodeCall(f, (arg1, arg2))` where the arguments are in a tuple.

**Comment by drortirosh** [comment]
@axic :
1.  while it is ultimately used by `staticcall`/`delegatecall`, it is often not used DIRECTLY. That is, it is passed to a constructor or a wrapper method to perform some other validation (or contract creation) first, as in the example "initCode" above.
2. in term of risk-analysis, using the alternative `abi.encodeWithSelector`  is FAR MORE RISKY , as it contains no checking on types and encoding of a parameters.
3. Suggested alternate syntax (`abi.encodeCall(f, (args)`) is possible, though counter-intuitive. In several other languages and tools the "`method.encode()`", format was used, and AFAIK its more comprehensible.
  e.g https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-encodeabi

**Comment by axic** [comment]
> 1. while it is ultimately used by staticcall/delegatecall, it is often not used DIRECTLY. That is, it is passed to a constructor or a wrapper method to perform some other validation (or contract creation) first, as in the example "initCode" above.

I still don't understand how this can be used with the `initCode` context.

> 2. in term of risk-analysis, using the alternative abi.encodeWithSelector is FAR MORE RISKY , as it contains no checking on types and encoding of a parameters.

Sure, that's why we think `abi.encodeCall` is nice, as it would validate the input types.

> 3. Suggested alternate syntax (abi.encodeCall(f, (args)) is possible, though counter-intuitive. In several other languages and tools the "method.encode()", format was used, and AFAIK its more comprehensible.
e.g https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-encodeabi

From the linked web3js doc:
> `myContract.methods.myMethod([param1[, param2[, ...]]]).encodeABI()`

I would say this syntax is counter-intuitive, it suggests a chaining of a call and calling `encodeABI()` on the result.

**Comment by transmissions11** [comment]
> I would say this syntax is counter-intuitive, it suggests a chaining of a call and calling encodeABI() on the result.

how about something like `myMethod.encodeABI([param1[, param2[, ...]]])`
