### ISSUE TITLE
TypeError: Tuple component cannot be empty.

### ISSUE THREAD

**Issue by JohnAllen** [ethereum/solidity#3385]
When there's an extra comma in a return value tuple, this error throws.  It was not immediately apparent what the problem was based on the error.  The compiler error message points to the opening parens of the tuple and not the extra comma as well.

Should this error be more specific and/or add this possible case of there being an extra error?  Will submit a PR for this if so desired.

**Comment by axic** [comment]
Do you mean this?

```
contract C {
  function f() returns (uint,uint) {
    return (1,);
  }
}
```

```
return.sol:3:5: Error: Different number of arguments in return statement than in returns declaration.
    return (1,);
    ^---------^
```

**Comment by JohnAllen** [comment]
precisely

**Comment by JohnAllen** [comment]
close but actually points to the opening parentheses, like this and doesn't include the extra comma or contents of the return values at all.
```
return (
       ^
```

**Comment by JohnAllen** [comment]
I would say the behavior for when this happens in the parameter list is helpful and probably what could happen for `return tuple` as well <img width="1894" alt="screen shot 2018-01-07 at 7 11 28 am" src="https://user-images.githubusercontent.com/2800641/34650697-208055da-f37a-11e7-89f9-cfd2182afc2a.png">

**Comment by axic** [comment]
Ah okay, the problem you have is that if it spans multiple lines, only the first one is shown.

**Comment by axic** [comment]
Current behaviour:
```
contract C {
  function f() returns (uint,uint) {
    return (
      1,
    );
  }
}
```

will have an error message of:
```
3385.sol:3:12: Error: Tuple component cannot be empty.
    return (
           ^ (Relevant source part starts here and spans across multiple lines).
```

I think this is solved by that extra message added in #3640.

**Comment by Kayaba-Attribution** [comment]
Late to the party but got the same misleasing error:
```
TypeError: Tuple component cannot be empty.
   --> src/Bounty.sol:208:16:
    |
208 |         return (
    |                ^ (Relevant source part starts here and spans across multiple lines).
```
I think the error should be `trailing comma on tuple`

**Comment by cameel** [comment]
@Kayaba-Attribution This does not have to be a trailing comma. You'll get the same error for example in a situation like this:
```solidity
return (1, 2, , 3, 4);
```
It's really exactly what it says - a tuple component cannot be left empty in certain situations.

**Comment by Aomaf** [comment]
just remove the comma from the last element.
(worked for me)

**Comment by ashitbg** [comment]
have removed the comma  from the last element but still shows the same error

**Comment by BahadorGh** [comment]
I had the same error.
Removing the trailing comma solved my problem.
