### ISSUE TITLE
Constructors and payable

### ISSUE THREAD

**Issue by mijovic** [ethereum/solidity#8790]
Inheritance:
 - If base constructor is payable it is possible to inherit even with nonpayable or no constructor at all
 - If base constructor is non payable it is possible to inherit with any kind of constructor
Basically, everything is allowed here, all contracts can be deployed successfully.
Even calling payable base constructor from modifier list in derived constructor is fine

Revert:
 - If base constructor is payable and no constructor in derived contract, passing ether while constructing is fine
 - If base constructor is payable and derived constructor is not payable, it will revert

Setting value for constructor while calling new:
 - If constructor is non payable, value cannot be set with new (it doesn't compile)
 - If there is no constructor, no meter if it has payable or non payable base constructor, it fails compilation

I think we need to define this strictly, especially when inheriting from contracts with payable constructors. If not in old codegen, at least in Sol->Yul.

**Comment by chriseth** [comment]
In my opinion, we should derive the behaviour from the following principles:
 - inheritance rules should match those for functions in general.
 - it should be possible to set `value` if and only if the contract does not revert when sent ether during construction time.
 - the callvalue check for constructors should be the same as for functions (this also covers the case of a constructor not being defined)

**Comment by ekpyron** [comment]
Are we sure that this is a problem? Can't one argue that the whole construction should be "as payable as" the most derived constructor? What currently happens if there is a non-payable base constructor and a payable most-derived constructor and you send value to it? I'll check.
EDIT: non-payable base constructor and payable derived constructor allows sending value without reverting - that's what I'd expect and feels right.

**Comment by ekpyron** [comment]
So the current rule is rather simple:
The creation of a contract is payable, if and only if it has an explicit payable constructor. No exceptions and the base contracts and their constructors have no effect on that.

**Comment by chriseth** [comment]
That sounds rather reasonable and safe actually...

**Comment by chriseth** [comment]
I think the rule "it should be possible to set value if and only if the contract does not revert when sent ether during construction time." should still hold, though - not sure if this is the case.

**Comment by ekpyron** [comment]
Only one direction currently holds: if it is possible to set value, then the contract does not revert, when sent ether during construction time.

The converse doesn't hold if there is no explicit constructor, e.g. in the following case:
```
contract A {
        constructor() public payable {}
}
contract B is A {
//      constructor() public {}
}
contract C {
    function f() public payable returns (uint256) {
        bytes memory c = type(B).creationCode;
        B b;
        // b = new B{value: 10}(); isn't allowed
        assembly {
            b := create(10, add(c, 0x20), mload(c)) // but this doesn't revert
        }

    }
}
```

**Comment by ekpyron** [comment]
Actually even worse: even if the base constructor is non-payable, there won't be a callvalue check:
```
contract A {
        constructor() public {}
}
contract B is A {}
contract C {
    function f() public payable returns (uint256) {
        bytes memory c = type(B).creationCode;
        B b;
        // b = new B{value: 10}(); isn't allowed
        assembly {
            b := create(10, add(c, 0x20), mload(c)) // but this still doesn't revert
        }

    }
}
```

Code generation only puts in a callvalue check, if there is an explicit non-payable constructor or no constructor in the entire inheritance hierarchy.
I'd consider this a code generation bug, but I'm not sure we should fix it for old codegen, because it could break stuff...

**Comment by bshastry** [comment]
Out of curiosity:

`b := create(10, add(c, 0x20), mload(c)) // but this still doesn't revert`

Does this mean that the sent ether is irretrievable?

Edit: I think I mean if `f()` had `msg.value` of `10` and this was forwarded to the `create` call, the caller of `f()` loses `10` ether forever iiuc

**Comment by ekpyron** [comment]
@bshastry Yep - there may still be some function in ``A``, resp. ``B`` to retrieve the contract's balance, but there may very well not be (for contracts that are never supposed to hold any ether) - if you send ether to such contracts "by force", it'll be lost iiuc.
